import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ProductsContextProvider } from '@/utils/productsContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NEXT E-Commerce App by Yash Yadav',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ProductsContextProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ProductsContextProvider>
  )
}
